package com.barsifedron.candid.cqrs.domainevent;

/**
 * The middleware intercept your event on its way to or back from the event listeners.
 * Think of this as a chain of decorators, each one adding its own behaviour to the process.
 * <p>
 * This is an extremely powerful way to add common behavior to all your events processing.
 * Simple examples of middleware:
 * A middleware persisting all the events generated by your app.
 * A middleware logging the execution time taken to process your events etc...
 * <p>
 * To help you understand, a few examples are provided in the bus-cqrs-example project
 * <p>
 * See an alternative way of doing this in the `bus-cqs` module.
 */
public interface DomainEventBusMiddleware {

    void dispatch(DomainEvent event, DomainEventBus next);

}
