name: CI

# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://help.github.com/en/articles/configuring-a-workflow
# TODO use fixed os versions

on:
    push:
    pull_request:

jobs:

    build:

        name: "Check"

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                java: [8, 11, 17]

        runs-on: ${{ matrix.os }}

        steps:

            - name: "git clone"
              uses: actions/checkout@v2

            - name: "setup jdk"
              uses: actions/setup-java@v2
              with:
                  distribution: "temurin"
                  java-version: 17

            - name: "./gradlew build"
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: build -PtestJavaVersion=${{ matrix.java }}
              env:
                  CI: true

            - name: "git diff --exit-code"
              run: git diff --exit-code
